title:
  1: Impossible
  2: Impossible
testIn: |-
  10
  9
  3 -1 2 4 4 -1 4 2 -1
  -1 -1 3 -1 2 4 3 2 3 4
  4 -1 -1 3 5 -1 5 2 -1
  -1 4 0 4 -1 -1 -1 -1 -1 4
  kqqmrrssop
  kllmhinnop
  ggbchidejj
  WXbcYZdeff
  WXQRYZTaaV
  PPQRSSTUUV
  LLMMIJNNOO
  AHHCIJEKKG
  ABBCDDEFFG
isTest: 'false'
isValidator: 'true'