title:
  1: Brutal
  2: Brutal
testIn: |-
  10
  9
  3 4 3 2 2 4 3 4 4
  3 3 3 1 2 1 3 5 4 4
  2 3 3 4 2 3 3 5 4
  4 1 4 1 1 2 4 4 4 4
  kppmqqrrss
  kllmhnnjoo
  Zabchiijfg
  Zabcddeefg
  QWWSXXYYUV
  QRRSMTTOUV
  FGLLMNNOPP
  FGHHIIJJKK
  AABBCCDDEE
isTest: 'false'
isValidator: 'true'