title:
  1: Advanced
  2: Advanced
testIn: |-
  8
  7
  4 3 2 3 3 3 2
  2 4 3 3 1 2 2 3
  3 3 2 3 3 2 4
  3 3 4 3 1 3 1 2
  ABCCDDEE
  ABFGGHHI
  JJFKLLMI
  NOOKPQMR
  NSSTPQUR
  VWXTYYUZ
  VWXaabbZ
isTest: 'true'
isValidator: 'false'