title:
  1: Expert
  2: Expert
testIn: |-
  8
  7
  4 3 -1 1 -1 -1 -1
  3 -1 1 3 -1 3 -1 4
  -1 4 3 4 -1 -1 1
  3 -1 -1 2 -1 -1 -1 3
  ABBCDEFF
  AGGCDEHI
  JJKLMMHI
  NOKLPQRR
  NOSSPQTT
  UUVWWXYZ
  aaVbbXYZ
isTest: 'true'
isValidator: 'false'