title:
  1: Impossible
  2: Impossible
testIn: |-
  10
  9
  -1 2 4 -1 4 4 2 -1 3
  -1 -1 3 -1 2 4 3 2 3 4
  -1 2 5 -1 5 3 -1 -1 4
  -1 4 0 4 -1 -1 -1 -1 -1 4
  ABBCDDEFFG
  AHHCIJEKKG
  LLMMIJNNOO
  PPQRSSTUUV
  WXQRYZTaaV
  WXbcYZdeff
  ggbchidejj
  kllmhinnop
  kqqmrrssop
isTest: 'true'
isValidator: 'false'