title:
  1: Brutal
  2: Brutal
testIn: |-
  10
  9
  4 5 3 3 2 4 3 3 2
  3 3 3 1 2 1 3 5 4 4
  4 4 3 4 2 2 3 4 3
  4 1 4 1 1 2 4 4 4 4
  AABBCCDDEE
  FGHHIIJJKK
  FGLLMNNOPP
  QRRSMTTOUV
  QWWSXXYYUV
  Zabcddeefg
  Zabchiijfg
  kllmhnnjoo
  kppmqqrrss
isTest: 'true'
isValidator: 'false'