title:
  1: Impossible
  2: Impossible
testIn: |-
  10
  9
  -1 -1 -1 2 -1 -1 -1 5 4
  5 3 -1 3 -1 -1 -1 -1 -1 4
  -1 -1 -1 -1 1 -1 3 5 -1
  4 -1 2 4 -1 4 -1 4 2 4
  AABBCCDDEE
  FFGHHIIJJK
  LMGNNOPQRK
  LMSTUOPQRV
  WXSTUYYZZV
  WXaabbcdde
  ffgghhciie
  jkkllmnoop
  jqqrrmnssp
isTest: 'true'
isValidator: 'false'